//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active_Record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Active_Record()
        {
            this.Active_Record_Items = new HashSet<Active_Record_Items>();
        }
    
        public int RecordID { get; set; }
        public int ActiveID { get; set; }
        public string Record_Information { get; set; }
        public int Record_Money { get; set; }
        public System.DateTime Record_Date { get; set; }
        public int Statue { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public string Account { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Active_Record_Items> Active_Record_Items { get; set; }
        public virtual Active_Rule Active_Rule { get; set; }
    }
}
