//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library_BookImgae
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public Nullable<System.DateTime> Image_Date { get; set; }
        public string Image_Path { get; set; }
    
        public virtual Library_Book Library_Book { get; set; }
    }
}
