//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library_Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Library_Book()
        {
            this.Library_BookImgae = new HashSet<Library_BookImgae>();
        }
    
        public int id { get; set; }
        public string BookLanguage { get; set; }
        public string bookName { get; set; }
        public string BookType { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string summary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Library_BookImgae> Library_BookImgae { get; set; }
    }
}
