//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Conn : DbContext
    {
        public Conn()
            : base("name=Conn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Active_Record> Active_Record { get; set; }
        public virtual DbSet<Active_Record_Items> Active_Record_Items { get; set; }
        public virtual DbSet<Active_Rule> Active_Rule { get; set; }
        public virtual DbSet<Active_Type> Active_Type { get; set; }
        public virtual DbSet<Library_Book> Library_Book { get; set; }
        public virtual DbSet<Library_BookImgae> Library_BookImgae { get; set; }
        public virtual DbSet<Login_Log> Login_Log { get; set; }
        public virtual DbSet<Login_User> Login_User { get; set; }
        public virtual DbSet<parameter> parameter { get; set; }
    }
}
